### ISSUE TITLE
Configuração de conexão postgres usando Docker, Docker compose e AWS

### ISSUE THREAD

**Issue by JhonatanLop** [projetoKhali/api3#109]
# 🤔 Descrição breve <br>  
`Resumidamente, do que se trata esta tarefa?`

Esta tarefa envolve a criação de uma infraestrutura para executar um banco de dados PostgreSQL em um ambiente Docker, utilizando Docker Compose, e hospedar esse ambiente na AWS (Amazon Web Services).

<br>

# 🤓 Especificações <br> 
`Quais pontos importantes devem ser levados em consideração para a execução desta tarefa?`

- Configurar um arquivo Docker Compose para definir o serviço PostgreSQL.
- Utilizar uma imagem PostgreSQL oficial do Docker.
- Configurar variáveis de ambiente para definir a senha do banco de dados, o nome do banco de dados, etc.
- Configurar uma rede Docker para garantir a comunicação entre os contêineres.
- Criar um contêiner Docker para sua aplicação ou serviço que necessita da conexão com o PostgreSQL.
- Configurar permissões e segurança adequadas para o ambiente Docker.
- Hospedar o ambiente Docker na AWS, por exemplo, usando o serviço Amazon ECS (Elastic Container Service) ou Amazon EKS (Elastic Kubernetes Service).

<br>

# 💭 Sugestões  <br>
`Algumas sugestões para facilitar a conclusão ou garantir a qualidade da solução dessa tarefa`

- Use o Docker Compose para definir a infraestrutura do ambiente, incluindo o serviço PostgreSQL e quaisquer outros serviços ou aplicativos que você precisa.
- Mantenha as credenciais do banco de dados seguras, evitando armazená-las diretamente no arquivo Docker Compose. Você pode usar variáveis de ambiente ou outras soluções para gerenciar senhas de forma segura.
- Ao hospedar na AWS, considere a escolha do serviço apropriado com base em suas necessidades de escalabilidade e gerenciamento, como ECS para contêineres ou EKS para orquestração de Kubernetes.
- Certifique-se de que a instância AWS onde você está hospedando o ambiente tenha as configurações de segurança adequadas, como grupos de segurança e políticas IAM (Identity and Access Management).
- Lembre-se de documentar todo o processo e configurar alertas ou monitoramento adequados para garantir o funcionamento contínuo do ambiente PostgreSQL.

**Comment by paulo-granthon** [comment]
futuramente
