### ISSUE TITLE
Estruturação do banco de dados

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api3#14]
# 🤔 Descrição breve <br>  
 - Criar as tabelas no banco de dados, definindo constraints, chaves primárias, chaves estrangeiras e enums, se necessário. Também, criar funções e triggers, se aplicável.

Objetivo: Estruturar o banco de dados de acordo com os requisitos do projeto.

<br>

# 🤓 Especificações <br> 
- [x] Deve conter a documentação necessária, assim como as modelagens.
- [ ] Levar em consideração a utilização do JPA dentro do projeto

<br>

# 💭 Sugestões  <br>
 - o @JhonatanLop gostaria muito de ajudar nessa tarefa <3

<br>

**Comment by JhonatanLop** [comment]
terminai o diagrama ERD das tabelas



![Image](https://github.com/projetoKhali/api3/assets/111443621/8391a4a2-3625-4f77-ae79-b1b0a35e4e50)

**Comment by JhonatanLop** [comment]
link para visualização no lucidchart
[Diagrama ERD](https://lucid.app/lucidchart/419ccc8f-50e8-4264-8552-5bb74b414d12/edit?viewport_loc=200%2C163%2C2018%2C940%2CHWEp-vi-RSFO&invitationId=inv_4c2fce34-2aca-422a-8331-2e759cd1c8ac)
