### ISSUE TITLE
Mapeamento Base para a construção de uma API REST

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api3#2]
Tarefa: 

- Identificar quais operações serão utilizadas no sistema, criação de um fluxograma da API. Analise do projeto anterior e constatação das melhorias e necessidades.

O que esperamos dessa entrega:

- fluxograma das APIs, mapeamento e listagem dos métodos HTTP a serem usados

**Comment by MikaelaBgtt** [comment]
1 POST/GET/PUT/para cada entidade;
1 GET membro_cr e verba;

>> Parametrização não tem método

Funcionalidades de listar todos os usuários e usuário específico: GET e GET por ID;

Funcionalidade de obter todos os apontamentos e apontamentos de um usuário específico, e para os 3 parâmetros (estados) diferentes: GET/GET por ID, GET aprovados, GET pendentes, GET recusados; (ou pode ser feito apenas dois métodos e a tratativa do que será ou não renderizado, feita no front-end)*;

Funcionalidade de atualizar o estado da aprovação - PUT, para mudar como aprovado ou recusado.

Método pro login (autenticação) - POST

Seleção de apontamentos pelo CR - GET pelo CR

Para a exibição dos gráficos, será uma requisição GET simples com a plotagem dos dados no front-end.

**Comment by JhonatanLop** [comment]
Também foi identificado um método para a funcionalidade de exportação de arquivo CSV.
obs:
Tenho uma ideia de como fazer via banco, um código SQL que exporta toda uma tabela em um arquivo CSV onde é possível definir o separador (oque nos causou problemas no semestre passado, pois ao abrir no excel o formato estava diferente do usual da 2RP)
No caso não tenho ideia de qual método HTTP seria, é preciso refinar essa ideia.

**Comment by JhonatanLop** [comment]
Fluxograma de ações do colaborador V1.0
![Image](https://github.com/projetoKhali/api3/assets/111443621/19fcd7d7-fa1a-4ab9-a168-cda0aaaa2917)

**Comment by JhonatanLop** [comment]
fluxograma de ações do gestor V1.0

![Image](https://github.com/projetoKhali/api3/assets/111443621/632fa2d6-5f89-4378-aaf3-d5f2b5226aca)

**Comment by JhonatanLop** [comment]
fluxograma de ações do Administrador V1.0

![Image](https://github.com/projetoKhali/api3/assets/111443621/f2841020-a555-4a48-9a75-e56f26c9168c)

**Comment by JhonatanLop** [comment]
link de exibição do fluxograma:
[Lucidchart](https://lucid.app/lucidchart/ac05d574-a6a8-463f-a8aa-adf17321ac35/edit?viewport_loc=2355%2C134%2C2029%2C991%2C0_0&invitationId=inv_a13d9b11-e0bf-414b-a031-3c0e2124e37a)
