### ISSUE TITLE
Criação do endpoint /usuarios

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api3#20]
# 🤔 Descrição breve <br>  
 - Criação do endpoint "/usuario" que terá os métodos HTTP que irão interagir com a classe usuário.
 
as subatividades dessa tarefa são:
- #44 
- #35
- #36 
- #17 
- #16 

<br>

# 🤓 Especificações <br> 
 - Story: Como administrador preciso ser capaz de cadastrar colaboradores, gestores e administradores para que eu possa designá-los as permissões corretas no sistema.

<br>

# 🚧 Dependências  <br>
`Essa tarefa depende de outras tarefas estarem concluídas? Insira o #ID do(s) Issue(s)`

 - #16 

<br>

**Comment by paulo-granthon** [comment]
Já havia iniciado o desenvolvimento previamente a alteração de assigned do issue
