### ISSUE TITLE
Criação do Método de Lançar um Apontamento

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api3#34]
# 🤔 Descrição breve <br>  

 - Implementar um método que recebe dados em formato JSON, converte esses dados em objetos da classe Apontamento e os insere no banco de dados usando o método repository.save().

Objetivo: Permitir que os usuários registrem apontamentos enviando informações em formato JSON através da API

<br>

# 🤓 Especificações <br> 
 - Story: Como colaborador preciso ser capaz de apontar as minhas horas extras e sobreavisos no sistema para que meu salário seja corretamente calculado.
 
 - INSERT/POST

<br>  

# 🚧 Dependências  <br>

 - #19 

<br>

**Comment by JhonatanLop** [comment]
feita a atividade. É possível realizar apontamento

![image](https://github.com/projetoKhali/api3/assets/111443621/98c1fe37-9091-4427-83f8-bf26ea7f2ea0)
