### ISSUE TITLE
Criação do método para Visualizar apontamento registrados por um usuário 

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api3#40]
# 🤔 Descrição breve <br>  

 - Implementar um método que retorna apontamentos relacionados a um usuário específico.
Objetivo: Facilitar a visualização dos apontamentos de um usuário específico.

<br>

# 🤓 Especificações <br> 

 - Story: Como colaborador preciso ser capaz de visualizar o meu histórico de apontamentos para acompanhar se foram registradores corretamente.

<br>

# 🚧 Dependências  <br>
`Essa tarefa depende de outras tarefas estarem concluídas? Insira o #ID do(s) Issue(s)`

 - #37 

<br>

**Comment by JhonatanLop** [comment]
método funcionando!!!!

![image](https://github.com/projetoKhali/api3/assets/111443621/e7c9fee0-d9b2-408a-a142-34cd690d9d1b)
